### ISSUE TITLE
Show stroybooks in web style.

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#302]
Ref: https://6224dd6a6655cb003a07b79c-kjvfapabcf.chromatic.com/?path=/docs/welcome--page
https://github.com/storybookjs/react-native

**Comment by karthiknmenon** [comment]
https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/get-started/
Just a reference from storybook.

**Comment by sangameshsomawar** [comment]
Closing this issue as react native storybook and web storybook renders differently.
