### ISSUE TITLE
TextInput component UI issues. 

### ISSUE THREAD

**Issue by Tsudhishnair** [bigbinary/neeto-ui-rn#307]
Check/Fix the following items in the TextInput component.

- [x]  Fix height of input components.

- [x]  Add right padding.

- [x] Update the name of the callback function to onChangeText.

- [x]  Update the fontSize and make it consistent with the design shared. 

- [x] Check the issue where animation is not working properly when the value is prefilled.

**Comment by sangameshsomawar** [comment]
@Tsudhishnair 
 - [ ]  In SearchBar component pass `rest` to parent `Container`
