### ISSUE TITLE
Typography and Guidelines

### ISSUE THREAD

**Issue by KiranRaj7** [bigbinary/neeto-ui-rn#313]
Added Typography styles and guidelines with respect to categories and component.

[Figma Typography](https://www.figma.com/file/GvxNW24y6lmKkrzdZCIz2e/Design-System?node-id=545%3A1814)

With Reference: [ios-human-interface-guidelines](https://developer.apple.com/design/human-interface-guidelines/foundations/typography/)

@sangameshsomawar @karthiknmenon @vysaghsekharbb @jenipharachel @Tsudhishnair @souravbaranwal

**Comment by sangameshsomawar** [comment]
@KiranRaj7 We are following same guidelines, closing this task.
