### ISSUE TITLE
Calendar component improvements.

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#321]
Add options to highlight selected days in different colors based on scenarios.

**Comment by sangameshsomawar** [comment]
@kamolesh97: As discussed last time, Rendering day with custom component was easy. I just passed the`dayComponent` to the `Calendar` component and it worked. But in neetoInvoice, we wanted to apply different styles for `todays date`, `selected date`, `date on which time is logged`, `date on which time is not logged`.  This requirement looked app specific. So instead of getting all data and making calculations in the library, I passed `dayComponent` directly from neetoInvoice.

Here is the PR: https://github.com/bigbinary/neeto-invoice-rn/pull/380/files

Should we go ahead with this? or do you have any other ideas? 🤔 If no then we can close the issue.

**Comment by kamolesh97** [comment]
@sangameshsomawar yes since the UI changes are app-specific, we can close this issue, closing it.
