### ISSUE TITLE
Toast content gets overflowed. 

### ISSUE THREAD

**Issue by Tsudhishnair** [bigbinary/neeto-ui-rn#326]
<img width="486" alt="Screenshot 2022-07-27 at 5 11 00 PM" src="https://user-images.githubusercontent.com/25509500/181238401-3067cb06-b22d-4230-8332-7c7d8bd90bdf.png">

**Comment by Tsudhishnair** [comment]
Also the toast button doesn't have the close icon in the end.

**Comment by sangameshsomawar** [comment]
@injas-bigbinary _a Please check
