### ISSUE TITLE
Have date format util function like we have in web.

### ISSUE THREAD

**Issue by Tsudhishnair** [bigbinary/neeto-ui-rn#332]
Ref: https://github.com/bigbinary/neeto-commons-frontend/issues/79

**Comment by Tsudhishnair** [comment]
@sangameshsomawar I was just thinking if we can also have a similar util function like we have in web.

**Comment by Tsudhishnair** [comment]
@sangameshsomawar  Notes from our initial discussion:
- We will have `neeto-commons-rn` lib similar to the web.

The lib will contain the following items

- **Components**
This will contain generic components which we are using across the neetoApps like the `Login` workflow etc. 

- **Hooks**
Will contain hooks used across the apps like `useDebounce`, `useKeyboard`, `useNotification` etc.

- **Helper functions/Config**
Will contain config files like `axios`, `keychain`, `asyncStore`, `localization`, `dayJs utils` etc.

**Comment by sangameshsomawar** [comment]
@Tsudhishnair Yes.

Like `@bigbinary/neeto-commons-rn/utils`, `@bigbinary/neeto-commons-rn/components`, `@bigbinary/neeto-commons-rn/hooks`

**Comment by sangameshsomawar** [comment]
@sangameshsomawar _a

**Comment by sangameshsomawar** [comment]
@neerajdotname We are thinking to create `neeto-rn-commons` to extract all common stuff. As of now, we are repeating Login /OTP Verification /Organization Selection Screens, and configurations like notifications, Axios, async storage, and keychain in each neeto RN app.  Should we go ahead with that?

**Comment by neerajdotname** [comment]
Sure. I thought we had already done that. Let’s do it.

**Comment by sangameshsomawar** [comment]
@kamolesh97 We already have one in neetoDesk. Just need to move to neetoCommons.

**Comment by sangameshsomawar** [comment]
@Tsudhishnair Closing this issue as we have added date utils in `neeto-commons-rn` now
