### ISSUE TITLE
update background color on onboarding screen (check with dark mode)

### ISSUE THREAD

**Issue by souravbaranwal** [bigbinary/neeto-ui-rn#333]
![Simulator Screen Shot - iPhone 13 - 2022-07-28 at 15 43 47](https://user-images.githubusercontent.com/25584161/181482058-ecb12c42-fa00-457b-8b74-4de08279c2c8.png)

**Comment by sangameshsomawar** [comment]
@injas-bigbinary _a Please check

**Comment by injas-bigbinary** [comment]
@souravbaranwal Please try adding `ParentView` to the component and see if that fixes the issue.
