### ISSUE TITLE
Multiline input text is going out in top and bottom. Not sure whether issue is in library or neetoInvoice

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#362]
https://user-images.githubusercontent.com/93119254/182933283-53dd198a-3885-469b-843d-132300884304.MOV

https://user-images.githubusercontent.com/93119254/182933641-186ec9db-cf82-4f77-92be-043916e4ab49.MOV

**Comment by Tsudhishnair** [comment]
The issue is with the Input component itself.

**Comment by sangameshsomawar** [comment]
@Tsudhishnair _a
