### ISSUE TITLE
Support gesture in SegmentPicker

### ISSUE THREAD

**Issue by souravbaranwal** [bigbinary/neeto-ui-rn#365]
User should be able to swipe the content to switch Tabs.

**Comment by injas-bigbinary** [comment]
@bigbinary/neeto-rn For this to work, we need to render the child components in the library itself right?

**Comment by sangameshsomawar** [comment]
@injas-bigbinary Just need to add something similar of https://github.com/bigbinary/neeto-ui-rn/blob/master/src/components/BottomSheet.js#L33 to https://github.com/bigbinary/neeto-ui-rn/blob/master/src/components/SegmentPicker.js#L124
