### ISSUE TITLE
Fix overflow issue with the label in ListItem component,  Match popup button design 

### ISSUE THREAD

**Issue by souravbaranwal** [bigbinary/neeto-ui-rn#368]
Ref: Popup button radius looks different
 https://www.figma.com/file/GvxNW24y6lmKkrzdZCIz2e/Design-System?node-id=471%3A1418

![182923388-94e3ce75-c361-4340-a33c-6ef104865b90](https://user-images.githubusercontent.com/25584161/183059391-7f9266ed-1cd4-4f97-b477-9267b7e28295.jpeg)

**Comment by sangameshsomawar** [comment]
@souravbaranwal _A Please work on this.

**Comment by souravbaranwal** [comment]
closing as duplicate issue of #382
