### ISSUE TITLE
Typography props improvements 

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#369]
@bigbinary/neeto-rn : I think we should add `fontFamily`, `color`, `fontSize` as required prop. This will help us in avoiding a lot of issues. agree ??

**Comment by Tsudhishnair** [comment]
If we are making it default then through out the application we need to specify these 3 fields right. If we don't specify anything it should be taking the generic body styles. ie: `sf400`, `font.primary` and `14`. 
Specifying these 3 fields all the time seems to be an extra task to me.

**Comment by sangameshsomawar** [comment]
@Tsudhishnair  @bigbinary/neeto-rn 

My whole point is to make everyone alert with `fontFamily`, `color`, `fontSize`.

Lets see an example: In neeto Desk (origin/388-ticket-details-screen-revamp) we have 81 `<Typography>` components and `fontFamily` is only given in 26 places. As we don't have any default `fontFamily` in the library, 55 places (81-26) we are using RN default font. 

Now coming to your point, even if we add `sf400` in the library as the default `fontFamily`, do you think all 55 should be `sf400`?

So what I am thinking is,if we get proptype error then the developer will be explicitly passing these 3 props by checking designs.

<img width="462" alt="Screenshot 2022-08-05 at 11 39 28 PM" src="https://user-images.githubusercontent.com/93119254/183136071-6ca419d0-7424-429d-b1b0-91723890bf3d.png">
<img width="487" alt="Screenshot 2022-08-05 at 11 40 10 PM" src="https://user-images.githubusercontent.com/93119254/183136084-0cb8cb17-6e3b-4d4e-b05d-12e7b7404179.png">

Another example, neetoInvoice. 38`<Typography>` components and only 18 places `fontFamily` is passed and 11 places color is passed. so all other places we might be rendering text in black default color. 

<img width="484" alt="Screenshot 2022-08-05 at 11 49 39 PM" src="https://user-images.githubusercontent.com/93119254/183138078-1064c298-a9e0-4467-a9e5-6a2cc13ef069.png">
<img width="487" alt="Screenshot 2022-08-05 at 11 50 40 PM" src="https://user-images.githubusercontent.com/93119254/183138066-258f07f0-47e6-4d2c-b44f-2b6301c62ffa.png">
<img width="491" alt="Screenshot 2022-08-05 at 11 49 29 PM" src="https://user-images.githubusercontent.com/93119254/183138081-83fbdd2f-178c-4740-8a9c-b0ba7029845b.png">

**Comment by Tsudhishnair** [comment]
Just noting down the points discussed over the call. 
Since in majority of the places we are using a particular set of styles like `fontFamily: sf400 `,  `color:grey800`,  `fontSize: 14`. We will be making this as the default style for the Typography component and will see if this works fine. 
If we find that using this approach, the chances of having inconsistency in the font styles shared in Figma wrt the one used code are more, then we will try using the above shared approach where these props will be made as required props for the Typography component.
