### ISSUE TITLE
Button props improvement.

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#375]
Currently, we have to use the below syntax for customizing labels.
```
<Button
  labelStyle={{
    fontFamily: "sf700",
    color: theme.colors.font.base,
   fontSize={"l"}
  }}
  variant="text"
  onPress={() => {
  }}
  label="Test"
/>
```

can we make changes to pass color, fontFamily and fontSize easily.

```
<Button
  fontFamily={"sf700"}
  color={theme.colors.font.base}
  fontSize={"l"}
  variant="text"
  onPress={() => {
  }}
  label="Test"
/>
```

**Comment by sangameshsomawar** [comment]
@bigbinary/neeto-rn Let me know your thoughts.

**Comment by injas-bigbinary** [comment]
@sangameshsomawar In this approach can we update label style apart from font and color?

**Comment by kamolesh97** [comment]
@sangameshsomawar I am fine with both, just that labelStyle adds a small separation between Button props and label props, once we add the type definitions, things will get even easier.

**Comment by sangameshsomawar** [comment]
@kamolesh97 @injas-bigbinary: 99% time the only requirement for changing label style is for `fontSize`, `color` and `fontFamily`.
So if we make it support directly then it will look clean I think. Still, we keep the `lableStyle` prop if the requirement comes to customize any other style.
