### ISSUE TITLE
Support `openAccordion` and `closeAccordion` methods.

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#376]

**Comment by sangameshsomawar** [comment]
@injas-bigbinary: Currently we have `toggleAccordion` function.  So if the use case is to close or open then first we need to subscribe to `onStateChanged` then set the state locally and then use that state to determine whether to toggle it or not.
I think we should support `openAccordion` and `closeAccordion` functions and manage state internally. Still we can keep  `toggleAccordion` and `onStateChanged`. 

Let me know your thoughts.

**Comment by injas-bigbinary** [comment]
@sangameshsomawar Ok. Will add.
