### ISSUE TITLE
Close button is not working in Toast

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#381]
https://user-images.githubusercontent.com/93119254/183465999-f3bb1cc2-2545-458e-8696-b266b87a969e.MOV

**Comment by injas-bigbinary** [comment]
@sangameshsomawar Debugged the issue and found an issue within the library itself. The hide method from the library isn't closing the Toast when we hold and release the toast.

**Comment by sangameshsomawar** [comment]
@injas-bigbinary  I will debug once.

**Comment by sangameshsomawar** [comment]
@Tsudhishnair _a Please check once.
