### ISSUE TITLE
Add option to customize tab bar height from user end

### ISSUE THREAD

**Issue by jenipharachel** [bigbinary/neeto-ui-rn#392]
https://github.com/bigbinary/neeto-ui-rn/blob/ffdc8d1b3ba09b3e90ea65a5611e7bd4b29a6cb4/src/components/BottomTabBar.js#L156

**Comment by sangameshsomawar** [comment]
@jenipharachel Instead of customizing height from the user end, can we conditionally specify different heights for android and iOS?

**Comment by jenipharachel** [comment]
@jenipharachel _a
