### ISSUE TITLE
MultiSelect component issues and additional requirements. 

### ISSUE THREAD

**Issue by Tsudhishnair** [bigbinary/neeto-ui-rn#439]
**Requirements**

- [ ]  View only option. ( Based on a prop we should be able to enable and disable the item selection, the same should be handled for `create` functionality in the component )

- [ ] No result message is required when the search result is empty and when the `createButton` prop is false. 

- [ ] Limit the number of tags shown in the Input component and show info like `8 more` or something similar to let the user know of other selected tags. 

**Issues**
- [ ]  Search filter is not working properly. We might have to remove `Fuse.js` and use a different approach like done in web which is handle by `react-select`. 

- [ ] We don't need the `select option` label. As per the new design we don't have that.
 <img width="367" alt="Screenshot 2022-08-24 at 11 49 26 AM" src="https://user-images.githubusercontent.com/25509500/186345066-56dc524b-0ec1-47e3-84b2-bd776d8f0506.png">

**Comment by Tsudhishnair** [comment]
@injas-bigbinary _a

**Comment by Tsudhishnair** [comment]
@KiranRaj7 We were thinking of limiting the number of selected tags shown in the main Input component to 3 or 4 and having a tag or text like `8 more` which will let the user know that there are 8 more selected tags. 
This would help in restricting the amount of space that the component will take if there are more selected tags. Since we are showing the complete list of tags in the bottomsheet, so the users can still check what all tags they are selected. 

If you also agree with this change then just let us how we need to show the `more tags` label.

**Comment by KiranRaj7** [comment]
Yes, we can have the 5th tag to be like "+8 more" and then redirect to bottom sheet.
@Tsudhishnair

**Comment by Tsudhishnair** [comment]
@KiranRaj7  Should there be any differentiation between the normal and this tag.
