### ISSUE TITLE
Cancel button is not rendering properly while animating and cutting in real iPhone XS MAX

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#445]
https://user-images.githubusercontent.com/93119254/186332972-bdde75f8-190d-463b-96ed-f058b468911f.mov

**Comment by sangameshsomawar** [comment]
![image](https://user-images.githubusercontent.com/93119254/186334550-5f61444e-c164-4775-accd-7b9e31104257.png)

**Comment by sangameshsomawar** [comment]
<img width="528" alt="Screenshot 2022-08-24 at 10 51 14 AM" src="https://user-images.githubusercontent.com/93119254/186335480-af684830-6165-4972-9406-31a9cf644dd1.png">

**Comment by Tsudhishnair** [comment]
@sangameshsomawar I am not able to reproduce the issue where Cancel button is getting overflowed out of the screen like shared above. 
Apart from iphone XS , I tried in iPhone SE, iphone 8 as well. Also added additional horizontal margin and still its working fine. 
<img width="561" alt="Screenshot 2022-08-24 at 12 44 55 PM" src="https://user-images.githubusercontent.com/25509500/186358495-509cdf2e-e785-41ce-b635-f8540f4fa662.png">
<img width="561" alt="Screenshot 2022-08-24 at 12 45 54 PM" src="https://user-images.githubusercontent.com/25509500/186358520-2be930e2-e1a0-4910-8fca-fc1b8b59114e.png">
