### ISSUE TITLE
Set Text Selection and Cursor color.

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#454]
<img width="551" alt="Screenshot 2022-08-29 at 12 12 34 PM" src="https://user-images.githubusercontent.com/93119254/187139323-64f6c580-c779-4470-98a8-cef6be6a0ccb.png">
<img width="551" alt="Screenshot 2022-08-29 at 12 12 31 PM" src="https://user-images.githubusercontent.com/93119254/187139345-a81732f8-9597-4bca-bfdd-925b066ad3cc.png">

**Comment by sangameshsomawar** [comment]
@KiranRaj7 Currently we are not setting any custom color for cursor and selection text. We can use theme-based colors. Please suggest some colors and document in Figma design system.

**Comment by KiranRaj7** [comment]
We can use #C7CDFD or 30% Opacity of Primary Color (#4558F9).
@sangameshsomawar
