### ISSUE TITLE
Research on creating section list using FlashList.

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#466]
Ref: https://github.com/bigbinary/neeto-chat-rn/issues/370

**Comment by kiran-kumar011** [comment]
Hi @sangameshsomawar,
I went through the video attached in [neeto-chat-rn](https://github.com/bigbinary/neeto-chat-rn/issues/370). Just to confirm whether I'm understanding this feature correct.

Basically we should implement a stickyHeader which should update dynamically while scrolling based on date?

**Comment by sangameshsomawar** [comment]
@kiran-kumar011 Currently we are using SectionList from react native. and we already have an Animated Flash list. As part of this issue, we need to figure out a way for creating SectionList from FlashList. This would be the first step. Then we will think on making headers sticky.

**Comment by kiran-kumar011** [comment]
@sangameshsomawar went through the documentation of creating `SectionList` from `FlashList` and found that the implementation depends on formatting the data before passing it to `FlashList`.

I have made some changes locally to verify the behaviour and it works as expected, even the stickyHeaders can be implemented using `FlashList`.

**Comment by sangameshsomawar** [comment]
@kiran-kumar011 I went through your branch `https://github.com/bigbinary/neeto-form-rn/tree/sectionlist-using-flashlist`. Looks good to me, please make changes to the real data and raise PR for neetForm first.
Design: https://www.figma.com/file/ybBpIJozKsMRkex1rWNX17/neetoForm?node-id=23%3A4148

**Comment by sangameshsomawar** [comment]
@injas-bigbinary As discussed on the call, we can use a section list directly from the library instead of creating a wrapper from flash list. Closing this issue.
