### ISSUE TITLE
Revert animation related changes.

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#479]

**Comment by sangameshsomawar** [comment]
@jenipharachel Had a discussion with @Tsudhishnair and @souravbaranwal, and we all feel that the animation looks slow. Can we revert the changes related to speed? Still, we can keep it as `default` instead of `fancy` mode. Let me know your thoughts.

**Comment by jenipharachel** [comment]
@sangameshsomawar I have updated the animation timing only for the Bottomsheet component since @karthiknmenon felt the bottom sheet closing was a bit hard. I can revert this change if he's okay with it.

Ref: https://github.com/bigbinary/neeto-ui-rn/pull/469/files

**Comment by karthiknmenon** [comment]
Sounds good to me.
