### ISSUE TITLE
New loader

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#482]
@KiranRaj7 _a currently we are showing default react native loader, we cannot show neeto loader same as web because it will not look good in all scenarios and it will look big as well. 
Could you please share some simple circular loader which we can use in all neetoRN apps.

https://user-images.githubusercontent.com/93119254/189488896-582a7c8a-a6de-4f93-8673-a47e2e6c4cca.MOV

**Comment by KiranRaj7** [comment]
Check this loader animations.
https://lottiefiles.com/97739-loader
https://lottiefiles.com/98915-loader
@sangameshsomawar

**Comment by sangameshsomawar** [comment]
@bigbinary/neeto-rn Which one did you like? I liked 2nd one as it looks fast and creates the illusion that something is loading faster.

**Comment by KiranRaj7** [comment]
Same thought. Can go with second.
@sangameshsomawar

**Comment by souravbaranwal** [comment]
I also like the 2nd one.

**Comment by kamolesh97** [comment]
+1 for 2nd

**Comment by Tsudhishnair** [comment]
Both looks good to me 😅 .

**Comment by sangameshsomawar** [comment]
@KiranRaj7 _A
