### ISSUE TITLE
SegmentTopBar picker UI issue

### ISSUE THREAD

**Issue by Tsudhishnair** [bigbinary/neeto-ui-rn#488]
Ref: https://github.com/bigbinary/neeto-desk-rn/issues/467

<img width="800" alt="Screenshot 2022-09-13 at 10 12 50 AM" src="https://user-images.githubusercontent.com/25509500/189810603-a43470dd-25a8-405e-9711-8af4d9381af6.png">

**Comment by sangameshsomawar** [comment]
@kiran-kumar011 _a 

cc: @Tsudhishnair
