### ISSUE TITLE
Improve paddings of Input field.

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#489]
Ref: https://github.com/bigbinary/neeto-chat-rn/issues/473

**Comment by Tsudhishnair** [comment]
@KiranRaj7 The above change requires change in the height of the Input component, based on this other similar components height also needs to be updated, like the multiselect etc.
Please check and let me know how much height can be increased, and what other changes we need to do related to this in the other components.

**Comment by KiranRaj7** [comment]
The problem occurs in smaller devices right?
Let me check about the height but increasing height may cause the component h/w proportions.
@Tsudhishnair
