### ISSUE TITLE
DISCUSSION: `OptionMenu` component

### ISSUE THREAD

**Issue by injas-bigbinary** [bigbinary/neeto-ui-rn#498]
@bigbinary/neeto-rn 

Since we've edit and delete options for most of the apps, can we have a common component in the library itself?

**Comment by sangameshsomawar** [comment]
@injas-bigbinary Please give some examples. Are you referring to the bottom sheet ? 🤔

**Comment by injas-bigbinary** [comment]
@sangameshsomawar  Yes. We had discussed about this when working on `neetoInvoice`

**Comment by sangameshsomawar** [comment]
@injas-bigbinary Sorry I don't remember exactly, Can you post some video here explaining the issue.

**Comment by injas-bigbinary** [comment]
https://user-images.githubusercontent.com/87293196/190613626-d7f2d6eb-284e-4bdb-9d6e-80fd3925f6d6.mov

**Comment by sangameshsomawar** [comment]
@injas-bigbinary Yes got it, let's do it.
