### ISSUE TITLE
Add missing type definition in `index.t.js`

### ISSUE THREAD

**Issue by injas-bigbinary** [bigbinary/neeto-ui-rn#510]
Some components are missing all the types defined in the element. Please go through the components.
For eg:
`BottomSheet` misses `onBackdropPress` is missing. 

Update `Fab` import. In `index.t.js` it's `Fab` and the component name is `FAB`

**Comment by injas-bigbinary** [comment]
@Tsudhishnair _a

**Comment by sangameshsomawar** [comment]
@kiran-kumar011 _a

cc: @Tsudhishnair
