### ISSUE TITLE
Issue in the `CheckBox`

### ISSUE THREAD

**Issue by injas-bigbinary** [bigbinary/neeto-ui-rn#513]
`CheckBox` touchable area has been increased and due to this the host application having issues.

<img width="436" alt="Screenshot 2022-10-04 at 12 42 15 PM" src="https://user-images.githubusercontent.com/87293196/193761332-e53a7b5c-4ab8-4d03-a14f-aae4615e1fa1.png">

![Screenshot_1664868672](https://user-images.githubusercontent.com/87293196/193761357-2232355e-4101-4fed-b321-b942fb992b2d.png)

**Comment by injas-bigbinary** [comment]
@sangameshsomawar We can bypass this issue by wrapping the `CheckBox` in another `Container`. But we might have to do this for all the checkboxes. Is that a better approach?

<img width="406" alt="Screenshot 2022-10-04 at 1 09 58 PM" src="https://user-images.githubusercontent.com/87293196/193762279-4be231fa-a87d-4406-83d1-f976a7302b61.png">

**Comment by sangameshsomawar** [comment]
@injas-bigbinary _a I will check
