### ISSUE TITLE
RichTextEditor improvements

### ISSUE THREAD

**Issue by souravbaranwal** [bigbinary/neeto-ui-rn#519]
- [ ] Support for text size scaling with respect to the change in font size from the device.
- [ ] Support of image in the editor is broken. Some alignment/scaling issues.
- [ ] Option to close the keyboard when clicked outside the Editor, currently we can only close the Keyboard from the toolbar icon.
- [ ] Support of touched event when the Editor is focused.
- [ ] Support of disabled prop, which will disable the editor.

**Comment by sangameshsomawar** [comment]
@Tsudhishnair This is test notification http://www.google.com/

**Comment by chiragbhaiji** [comment]
> Support of image in the editor is broken. Some alignment/scaling issues.

@souravbaranwal can you please share some more details of this issue.

> Support of disabled prop, which will disable the editor.

To disable the RichTextEditor, `disabled` can be passed under `editorProps` object. @sangameshsomawar if needed in future maybe we can define our own interface to take such common props to our RichTextEditor and then pass is as needed for the pell editor or any other editor in future.

```jsx
<RichTextEditor
  ...
  editorProps={{
    ...
    disabled: true,
  }}
/>
```

**Comment by sangameshsomawar** [comment]
@chiragbhaiji : Closing this issue as we will be using normal text input.
