### ISSUE TITLE
Toast is overlapping with Dynamic Island

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/neeto-ui-rn#521]
<img width="575" alt="Screenshot 2022-10-14 at 5 08 48 PM" src="https://user-images.githubusercontent.com/93119254/195838089-07c75184-303f-442b-9b31-8f9849be5ab5.png">

**Comment by sangameshsomawar** [comment]
@kiran-kumar011 _A :  One possible solution is adding minor padding at the top conditionally. We can also check if there is a way to detect this with safe area handler.

**Comment by kiran-kumar011** [comment]
@sangameshsomawar ,
The default topOffsetValue is fixed in `react-native-toast-message` library itself because of that reason the toast is being overlapped with the dynamic island. 

https://github.com/calintamas/react-native-toast-message/issues/409
