### ISSUE TITLE
Notification Screen - Design

### ISSUE THREAD

**Issue by KiranRaj7** [bigbinary/neeto-ui-rn#545]
Added two design styles for notification screen. Let me know your thoughts and which one works better.

https://www.loom.com/share/0ad73664b27144359f1bc436a9607a55
https://www.figma.com/file/eqP1QJMgTaNQ6wo8C0zokQ/neetoChat?node-id=910%3A6561&t=pUQXbUwt1yxSLxsC-1

![Screenshot 2022-12-06 at 3 07 04 PM](https://user-images.githubusercontent.com/104344347/205874693-2294944d-aa5a-4378-84c6-26b645d2b314.png)

@sangameshsomawar @chiragbhaiji @Tsudhishnair

**Comment by sangameshsomawar** [comment]
@KiranRaj7 @chiragbhaiji how about this?

<img width="571" alt="Screenshot 2022-11-21 at 3 11 39 PM" src="https://user-images.githubusercontent.com/93119254/205917730-b2adb6c4-90d4-4ea9-b135-31889c8b9b5c.png">

**Comment by neerajdotname** [comment]
https://www.loom.com/share/027eca845e01452e9fc37960602616d6

**Comment by KiranRaj7** [comment]
@sangameshsomawar It will consume more spacing and padding. I think we can go with one Neeraj suggested.

CC: @neerajdotname
