### ISSUE TITLE
New App Icon and Splash Screen update

### ISSUE THREAD

**Issue by KiranRaj7** [bigbinary/neeto-ui-rn#554]
Splash Screen: https://www.figma.com/file/GvxNW24y6lmKkrzdZCIz2e/Design-System-Mobile?node-id=1621%3A7422&t=A5B0kfia7aQKiMzH-1

App Icon: https://www.figma.com/file/GvxNW24y6lmKkrzdZCIz2e/Design-System-Mobile?node-id=1619%3A7399&t=A5B0kfia7aQKiMzH-1

 - [x] neetoPlanner https://github.com/bigbinary/neeto-planner-rn/issues/759
 - [x] neetoChat https://github.com/bigbinary/neeto-chat-rn/issues/527
 - [x] neetoDesk https://github.com/bigbinary/neeto-desk-rn/issues/536
 - [x] neetoForm https://github.com/bigbinary/neeto-form-rn/issues/167
 - [x] neetoCal https://github.com/bigbinary/neeto-cal-rn/issues/73
 - [x] neetoInvoice https://github.com/bigbinary/neeto-invoice-rn/issues/501

**Comment by sangameshsomawar** [comment]
@KiranRaj7 Need help with android icons. 

https://app.usebubbles.com/rtpAsTvpcVGZjnMXyvL14K/sangamesh-s-video-recording

[res.zip](https://github.com/bigbinary/neeto-ui-rn/files/10276508/res.zip)

**Comment by KiranRaj7** [comment]
Yes, can you share the required sizes for android as mentioned in the video. I'll also create circular styles for the same.
@sangameshsomawar

**Comment by sangameshsomawar** [comment]
@KiranRaj7 Yes I have shared in the zip.

**Comment by KiranRaj7** [comment]
For Android App Icons. 
https://www.figma.com/file/GvxNW24y6lmKkrzdZCIz2e/Design-System-Mobile?node-id=1644%3A8803&t=oyxU9ouj52k7MsIQ-1

Please check if the naming is suitable.

@sangameshsomawar

**Comment by sangameshsomawar** [comment]
@KiranRaj7 Please check 

 https://app.usebubbles.com/3nkiErK4AsTWEgbBG4Utss/untitled-bubble

**Comment by KiranRaj7** [comment]
Yes, I'll correct the names.
@sangameshsomawar

**Comment by sangameshsomawar** [comment]
@KiranRaj7 also facing issues with radius in iPhone. 

https://app.usebubbles.com/v3ZaUU2FKii1bLDdrA7s2m/sangamesh-s-video-recording

**Comment by KiranRaj7** [comment]
Check [this](https://www.figma.com/file/GvxNW24y6lmKkrzdZCIz2e/Design-System-Mobile?node-id=1644%3A8803&t=4seFJXSUdMb1dB4S-1) 
Renamed icons

@sangameshsomawar

**Comment by sangameshsomawar** [comment]
@KiranRaj7 Please check 

https://app.usebubbles.com/agwugAqgi27NoSDDxyo21e?eid=ppbfhhgcdehhbjigifndnfmcihegokbb&focusTitle=true

**Comment by KiranRaj7** [comment]
Can you check now. It's probably because of grouping, I fixed that now.
@sangameshsomawar

**Comment by sangameshsomawar** [comment]
@KiranRaj7 https://app.usebubbles.com/9G8HqqJ7UXoLnFz4UC74bv/sangamesh-s-video-recording

**Comment by KiranRaj7** [comment]
@sangameshsomawar Let me check

**Comment by KiranRaj7** [comment]
Please find the app icons for Android devices.

[neetoCal.zip](https://github.com/bigbinary/neeto-ui-rn/files/10318186/neetoCal.zip)
[neetoChat.zip](https://github.com/bigbinary/neeto-ui-rn/files/10318189/neetoChat.zip)
[neetoDesk.zip](https://github.com/bigbinary/neeto-ui-rn/files/10318192/neetoDesk.zip)
[neetoForm.zip](https://github.com/bigbinary/neeto-ui-rn/files/10318194/neetoForm.zip)
[neetoInvoice.zip](https://github.com/bigbinary/neeto-ui-rn/files/10318197/neetoInvoice.zip)
[neetoPlanner.zip](https://github.com/bigbinary/neeto-ui-rn/files/10318199/neetoPlanner.zip)

[Figma](https://www.figma.com/file/GvxNW24y6lmKkrzdZCIz2e/Design-System-Mobile?node-id=1613%3A6109&t=BuUX0l8VcU6CIQT8-1)

@sangameshsomawar
