### ISSUE TITLE
Reply, Note and Forward Component Design Update - neetoDesk and neetoChat

### ISSUE THREAD

**Issue by KiranRaj7** [bigbinary/neeto-ui-rn#572]
Please check the design update for the input component. Let me know your thoughts.
https://www.loom.com/share/56a4ab5d90a6459ba973d2dd56b25417

[Figma ](https://www.figma.com/file/0U2YaGkfYfn8SAWrrLzEjW/neetoDesk?node-id=1717%3A13305&t=SM4lXsInc35ggviA-1)

@neerajdotname @sangameshsomawar @chiragbhaiji @Tsudhishnair

**Comment by sangameshsomawar** [comment]
@KiranRaj7

**Comment by KiranRaj7** [comment]
https://www.loom.com/share/dad0dbfa9c56485083f9600fb83f3bbc
@neerajdotname 

The icon stroke is same @sangameshsomawar [Design](https://www.figma.com/file/0U2YaGkfYfn8SAWrrLzEjW/neetoDesk?node-id=1717%3A13305&t=vifWl4aLPYeBBcuC-1)

**Comment by sangameshsomawar** [comment]
@neerajdotname: We tried something different, Need your views on the new design. 
https://app.usebubbles.com/vSvi3aEXPySj7Nk7iSDSJN/sangamesh-s-video-recording

cc: @KiranRaj7

**Comment by neerajdotname** [comment]
@sangameshsomawar Looks good to me. 👍 Infact I feel this is a better design. User has access to previous messages and things are consistent.

**Comment by sangameshsomawar** [comment]
@neerajdotname @KiranRaj7 The new chat input is fully functional in neetoChat now, I have pushed builds for neetoChat staging. Could you please check it on the real device and provide feedback?

**Comment by neerajdotname** [comment]
@sangameshsomawar I don't have neetoChat staging build on my phone. I've an iPhone. What do I need to do to get that build?

**Comment by sangameshsomawar** [comment]
@neerajdotname Is this the correct apple id? If yes, then please check the testflight app. neetoChat staging app should be visible.

If no then please share the apple id, I will invite.

<img width="1840" alt="Screenshot 2023-02-22 at 9 48 43 PM" src="https://user-images.githubusercontent.com/93119254/220688418-2370b07e-eb30-4c4a-8967-5b27a323365b.png">

**Comment by neerajdotname** [comment]
@sangameshsomawar Yes that's the correct apple id.

**Comment by sangameshsomawar** [comment]
@neerajdotname Then it shows that recently you installed the neetoChat Staging app on Feb 18. Could you please check testflight once.

**Comment by neerajdotname** [comment]
@sangameshsomawar Got it. I'll check it out. 

Staging builds are connected to `.net` on the backend?

**Comment by sangameshsomawar** [comment]
@neerajdotname Yes stagging app builds are connected to .net .
