### ISSUE TITLE
.rubyversion & Gemfile - Is this a ruby project?

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto-ui-rn#581]
@sangameshsomawar _a https://www.loom.com/share/9798206734e545c5beb0b1984f9f3145

**Comment by sangameshsomawar** [comment]
@neerajdotname These files are required as react native uses cocoa pods to install pod files for iOS and cocoa pod is a dependency added in the [gemfile](https://github.com/bigbinary/neeto-ui-rn/blob/main/Gemfile#L6).

**Comment by neerajdotname** [comment]
It seems Vercel doesn't support fine grained Ruby version. We'll stay with render.
