### ISSUE TITLE
Refactor `ChatInput` Component

### ISSUE THREAD

**Issue by paulsojan** [bigbinary/neeto-ui-rn#644]
- [ ] Fix UI inconsistencies while showing the cc/bb field with attachments.

**Comment by shashank-bhatotia** [comment]
@paulsojan: Will it be possible for you to share a few screenshots describing the UI inconsistencies? Or maybe a short neetoRecord video?

**Comment by paulsojan** [comment]
@shashank-bhatotia https://github.com/bigbinary/neeto-ui-rn/assets/47073691/e727f568-04e8-4473-b873-9d78416f2803

**Comment by shashank-bhatotia** [comment]
@paulsojan The expanded state (which shows the email fields) persist even after uploading the attachment. The expansion and contraction is now dependent solely on user's action by tapping the minimise/maximise icon:

https://github.com/bigbinary/neeto-ui-rn/assets/49222068/ccdb2761-d21e-4d7b-ab9b-315e233ca4a1
