### ISSUE TITLE
Follow the new UI theme changes

### ISSUE THREAD

**Issue by chiraggshah** [bigbinary/neeto-ui-rn#663]
@paulsojan _a

@praveen-murali-ind : Please go through the mobile app and check what changes we need to make apart from the button colors.

**Comment by praveen-murali-ind** [comment]
@Tsudhishnair Could you please check?

**Comment by Tsudhishnair** [comment]
@chiraggshah https://sudhish-nair.neetorecord.com/watch/12013ff4-d94c-44e1-943e-0648b77ae603
cc: @paulsojan @praveen-murali-ind 

- The base color can be updated to - #008068
- Success color can be updated to - #018d6d

**Comment by chiraggshah** [comment]
@Tsudhishnair : Sounds good.
